### PR TITLE
Add traffic lights handout

### PR DESCRIPTION
**Pull request by hroncok**
In case you'd like some  graphics:

https://openclipart.org/detail/287743/traffic-light

### CODE REVIEW

**Comment by hroncok** [comment]
I can also adapt this to vectors and add white if you like:

gif

**Comment by hroncok** [comment]
I'll rebase to #2 once merged.

**Comment by hroncok** [comment]
rebased

**Comment by encukou** [comment]
Thank you! I'll send a PR with improvement suggestions, and the graphic.

The train vector would be nice to have.

**Comment by hroncok** [comment]
FYI I'm working on the vector image

**Pull request merged**
